updations
suraj-soni-04/planner_3d pull request #2
Opened 2024-05-10 07:52 UTC by suraj-soni-04

2024-05-10 08:47 UTC, suraj-soni-04 commented
![Screenshot (145)](https://github.com/suraj-soni-04/planner_3d/assets/154866411/b88c5bd0-be95-402a-8d9d-e9a971bf3e0b)

2024-05-12 12:12 UTC, vinayaksutar commented on public/favicon.ico
Remove if not required

2024-05-12 12:21 UTC, vinayaksutar commented on src/reportWebVitals.ts
remove if not required

2024-05-12 12:21 UTC, vinayaksutar commented on src/logo.svg
remove if not required

2024-05-12 12:23 UTC, vinayaksutar commented on public/robots.txt
remove if not required

2024-05-12 12:23 UTC, vinayaksutar requested changes
Code cleanup

2024-05-12 15:49 UTC, suraj-soni-04 commented
Ok, doing the changes

2024-05-16 11:05 UTC, suraj-soni-04 commented on public/favicon.ico
removed

2024-05-16 11:05 UTC, suraj-soni-04 commented on src/reportWebVitals.ts
it was required

2024-05-16 11:05 UTC, suraj-soni-04 commented on src/logo.svg
removed

2024-05-16 11:05 UTC, suraj-soni-04 commented on public/robots.txt
removed

2024-05-16 11:06 UTC, suraj-soni-04 commented
suggested clean is done

2024-05-16 12:17 UTC, vinayaksutar approved these changes

2024-05-16 17:07 UTC, merged